Shutdown Circuit
olin-electric-motorsports/ESF pull request #16
Opened 2017-01-04 22:40 UTC by rileychapman

2017-01-07 22:13 UTC, aehoppe requested changes
Looks good. I left a few comments on small errors or things that could be a little clearer.

2017-01-07 22:13 UTC, aehoppe commented on esf_main.tex
> +		\item The GLV Master Switch (GLVMS) controls power to the entire low voltage system. As a result, high voltage cannot be present when the low voltage system is not active. The GLVMS has a lockout s
Including the AIRs

2017-01-07 22:13 UTC, aehoppe commented on esf_main.tex
> +		\item The Left E-Stop is a large red push-rotate button located at approximately the hight of the driver's head on the left side of the vehicle.
*height

2017-01-07 22:13 UTC, aehoppe commented on esf_main.tex
> +		\item The Brake System Plausibility Device (BSPD) holds a normally open relay closed when it has not detected an implausibility. When it does detect an implausibility, it latches in that state unti
it latches in a low state

2017-01-07 22:13 UTC, aehoppe commented on esf_main.tex
> +		\item The Battery Management System (BMS) monitors the condition of the accumulator. It holds a normally open relay closed while the Lithium cells are operating within safe temperature and electric
Lithium doesn't need to be capitalized.

2017-01-07 22:13 UTC, aehoppe commented on esf_main.tex
> +        \caption{Block Diagram of Shutdown Circuit}
We're going to have to figure out how to make a numbered list of figures somewhere down the line. I'll look at last year's ESF for reference

2017-01-08 03:16 UTC, rileychapman commented on esf_main.tex
> +        \caption{Block Diagram of Shutdown Circuit}
The list of figures should be generated automatically

2017-01-08 03:24 UTC, rileychapman commented
Made edits based on comments, also the work I have done on motor and motor controller have made it into this pull request

2017-01-11 19:13 UTC, merged

2017-01-11 19:13 UTC, aehoppe commented
Looks good to me