Wrote section for Ready to Drive Sound
olin-electric-motorsports/ESF pull request #17
Opened 2017-01-06 05:37 UTC by segerpeter07

2017-01-07 22:27 UTC, aehoppe requested changes
Please see my comments for a few changes I'd recommend. However, I think we'll have to redesign this entirely. There will not be TS wiring going into the dashboard. Let's set up a meeting to talk about this.

2017-01-07 22:27 UTC, aehoppe commented on esf_main.tex
> +	\includegraphics[width=\linewidth]{Schematic}
Please use a more descriptive file name. This file name will create conflicts down the line.

2017-01-07 22:27 UTC, aehoppe commented on esf_main.tex
> +According to these equations, a 1.2K$\Omega$ resistor will function as a current limiting resistor.
It'll have to be like a 10W power resistor as well. You should talk about where you're going to mount it to ensure that it gets adequate cooling.

2017-01-07 22:27 UTC, aehoppe commented on esf_main.tex
> +loud enough and underneath to assist with water proofing of the container
Is the buzzer waterproof?

2017-01-08 20:45 UTC, segerpeter07 commented on esf_main.tex
> +loud enough and underneath to assist with water proofing of the container
The new one I chose is 100% waterproof

2017-01-08 22:22 UTC, aehoppe requested changes
Your buzzer should be on the high side of the N-FET so that the FET changes the buzzer's connection to ground, not power.

2017-01-08 22:22 UTC, aehoppe commented on esf_main.tex
> +to the voltage. The last step in the start up sequence will notify the CAN system that it is time for the ready
This should say that the BMS will notify the Dashboard CAN node when the shutdown circuit is complete.

2017-01-08 22:22 UTC, aehoppe commented on esf_main.tex
> +Using the inverse square law for sound pressure levels, 123db at 10cm will translate to 117db at 2m which is well over the minimum SPL.
I'm not so thrilled with the volume of this buzzer, it's well into the territory where hearing it at close range will be dangerous to hearing. Can you find one a little quieter, like 100 dB?

2017-01-08 22:22 UTC, aehoppe commented on esf_main.tex
> +loud enough and is waterproof, so it doesn't require any extra protection besides a waterproof O-ring around the mounting point.
We'll probably end up using some waterproof silicone sealant like RTV for this for a more permanent seal once we're confident

2017-01-11 19:15 UTC, aehoppe requested changes

2017-01-11 19:15 UTC, aehoppe commented on esf_main.tex
> +The Ready to Drive sound is located as a component of the dashboard subsystem, and contains a buzzer (\href{http://www.mallory-sonalert.com/specifications/STA20502.PDF}{Link: Mallory Sonalert Product
Please provide a reference with \ref to a subsection of the appendix that shows a piece of the data sheet with volume charcteristics, and also has a hyperlink to the full datasheet, as per last year's ESF.

2017-01-11 19:15 UTC, aehoppe commented on esf_main.tex
> +Using the inverse square law for sound pressure levels, 97db at 122cm will translate to 93db at 2m which is a loud enough volume without inducing harm to the listener.
Also link to the appendix

2017-01-12 02:15 UTC, aehoppe requested changes
Just one more thing, please put the appendix section under Section 11 with the same subsection name as the section of the ESF as per last year's document.

2017-01-12 02:15 UTC, aehoppe commented on esf_main.tex
> +\subsection{Ready to Drive (APPENDIX SECTION)}\label{Ready to Drive}
Can you put this as a subsection after Section 11 (Appendix)? Sorry to keep running this back and forth.

2017-01-12 23:18 UTC, closed without merging