IMD and IMD reset sections (2.2 and 2.5)
olin-electric-motorsports/ESF pull request #18
Opened 2017-01-06 22:39 UTC by nrivkin

2017-01-07 22:06 UTC, aehoppe requested changes
We're actually using a TE Connectivity MICRO MATCH connector, I'd check the part number there.

2017-01-10 12:11 UTC, nrivkin commented
Fixed connector type and added mention of fuse

2017-01-11 19:21 UTC, aehoppe requested changes

2017-01-11 19:21 UTC, aehoppe commented on esf_main.tex
> +The  IMD uses the TYCO-MICRO MATE-N-LOK 1 x 2-1445088-8 connector and it's mate. It connects to the accumulator interface board, which sends the signal to a through a 28 AWG ribbon cable to the IMD l
As per last year's ESF, please provide a \ref to a section you create in the appendix for the IMD datasheet with the important parameters (and a hyperlink to the full datasheet), as well as a \ref to a section in the appendix where the fuse information will go. I will fill in the fuse information later today.

2017-01-11 19:21 UTC, aehoppe commented on esf_main.tex
> +The IMD latch will be connected to the ?? board via a 4-pin Molex LLC Ultrafit 1722861104 with 20 AWG wire, and the ?? board using a  6-pin TE Connectivity MICRO MATCH 338068-6 connector with 28 AWG
What are these question marks for? Also we need to figure out fusing for those wires and current and temperature ratings. Please reference last year's ESF for the important information to put here.

2017-01-12 11:30 UTC, nrivkin commented on esf_main.tex
> +The IMD latch will be connected to the ?? board via a 4-pin Molex LLC Ultrafit 1722861104 with 20 AWG wire, and the ?? board using a  6-pin TE Connectivity MICRO MATCH 338068-6 connector with 28 AWG
Are we using the wiring found here? 
Mouser Part #:
571-19711119
Manufacturer Part #:
1-971111-9

http://www.mouser.com/ProductDetail/TE-Connectivity/1-971111-9/?qs=tNpDSWKagOPkPLjfSGNYAA%3d%3d

2017-01-12 13:02 UTC, nrivkin commented
Added IMD datasheet, added refs, added what I could find about wire types. For 20 AWG (in the shutdown circuit) and 18 AWG (for power transmission) I do not know the exact wire we are using so I could not find voltage or temp ratings. I got current ratings from http://www.powerstream.com/Wire_Size.htm, and assuming our ribbon cable was the one found here, or at least had equivalent ratings.http://www.mouser.com/ProductDetail/TE-Connectivity/1-971111-9/?qs=tNpDSWKagOPkPLjfSGNYAA%3d%3d

2017-01-12 13:27 UTC, nrivkin commented on esf_main.tex
> +The  IMD uses the TYCO-MICRO MATE-N-LOK 1 x 2-1445088-8 connector and it's mate. It connects to the accumulator interface board, which sends the signal to a through a 28 AWG ribbon cable to the IMD l
done

2017-01-12 20:56 UTC, aehoppe commented
Please add that since the IMD will be in the accumulator, the wiring to it will be rated to at least 300V and at least 90C.

2017-01-13 06:29 UTC, closed without merging

2017-01-13 06:29 UTC, aehoppe commented
Closed because it was merged via a different PR