TSAL information and circuit image
olin-electric-motorsports/ESF pull request #20
Opened 2017-01-08 21:02 UTC by ljordan51

2017-01-08 22:26 UTC, aehoppe requested changes
Looks good, needs a few changes though. See comments. Also, thanks for picking this up on short notice!

2017-01-08 22:26 UTC, aehoppe commented on esf_main.tex
> +The circuitry designed has a TS-controlled optocoupler. When the TS is over 60V, zener diodes with a breakdown voltage of 58V and 3.6V respectably power the photodiode side which switches the mosfet
*respectively

2017-01-08 22:26 UTC, aehoppe commented on esf_main.tex
> +The circuitry designed has a TS-controlled optocoupler. When the TS is over 60V, zener diodes with a breakdown voltage of 58V and 3.6V respectably power the photodiode side which switches the mosfet
also MOSFET should probably be capitalized, along with Zener.

2017-01-08 22:26 UTC, aehoppe commented on esf_main.tex
> +The circuitry designed has a TS-controlled optocoupler. When the TS is over 60V, zener diodes with a breakdown voltage of 58V and 3.6V respectably power the photodiode side which switches the mosfet
Also reference the figure using \Fref{}

2017-01-08 22:26 UTC, aehoppe commented on esf_main.tex
> +All connections made by wires will be 20 AWG rated for 600V, 125°C and 7A, while all PCB traces will be a minimum of 12 mil, but nominally 20 mil in width. The TS voltage will be fused to 1A on the p
Good!

2017-01-08 22:26 UTC, aehoppe commented on esf_main.tex
> +The TSAL will be mounted to the underside of the highest point of the main roll hoop, per EV 4.12.3 & 4 using a robust 3D printed (Kevlar reinforced Nylon) bracket integrating the light and necessary
We'll want a CAD rendering for this probably.

2017-01-09 07:20 UTC, ljordan51 commented on esf_main.tex
> +The circuitry designed has a TS-controlled optocoupler. When the TS is over 60V, zener diodes with a breakdown voltage of 58V and 3.6V respectably power the photodiode side which switches the mosfet
do i need to add a label to the figure and/or put anything in the curly braces? or just type \Fref{} wherever i want to reference the figure? and what does Fref actually insert? Text with the the figure number?

2017-01-09 07:28 UTC, ljordan51 commented on esf_main.tex
> +The TSAL will be mounted to the underside of the highest point of the main roll hoop, per EV 4.12.3 & 4 using a robust 3D printed (Kevlar reinforced Nylon) bracket integrating the light and necessary
do i need to request one from someone in mechanical? if so, who? if not, where can i find the rendering?

2017-01-12 19:10 UTC, merged