Inertia switch
olin-electric-motorsports/ESF pull request #24
Opened 2017-01-12 00:47 UTC by aehoppe

Added section for inertia switch, even though it's identical to last year. It's not very fleshed out, but apparently it was good enough. Doesn't seem like it's that high-priority.

2017-01-12 01:07 UTC, byronwasti requested changes
Looks good. A render is needed, but for now a TODO is valid.

2017-01-12 01:07 UTC, byronwasti commented on esf_main.tex
> + The inertia switch will be located on the dashboard, in reach of the driver as to fit EV5.7.4. It is mounted properly (upwards), so it can be triggered and reset.
Are we not going to include a render here? I'm pretty sure it is required; I would put a `TODO` here so we remember to.

2017-01-12 01:07 UTC, byronwasti commented on esf_main.tex
> +            The Inertia switch will be wired to be normally closed and open the shutdown circuit in the case that there is a crash. The inertia switch is wired in-line with the shutdown circuit to be
This feels a bit wordy/repetitive. Possibly remove the part in the first sentence about the Inertia Switch being normally closed, and just leave that for the second sentence.

2017-01-12 02:07 UTC, aehoppe commented on esf_main.tex
> + The inertia switch will be located on the dashboard, in reach of the driver as to fit EV5.7.4. It is mounted properly (upwards), so it can be triggered and reset.
So this is exactly what we had last year, which I guess passed. I'll still put in a render.

2017-01-12 05:24 UTC, aehoppe commented
I added the inertia switch render.

2017-01-12 22:03 UTC, byronwasti commented
You might want to add a distinct circle around the switch, as of right now there is a lot going on and its hard to tell what to look at.

2017-01-13 21:18 UTC, aehoppe commented
Should be pretty visible. I added a yellow box around it.

2017-01-16 16:28 UTC, byronwasti approved these changes

2017-01-16 16:28 UTC, merged